### ISSUE TITLE
synced up and down, but not doing it any longer

### ISSUE THREAD

**Issue by tobowers** [playcanvas/playcanvas-sync#29] opened 2021-12-08 13:05 UTC
So this was working for me (and oh my god is it better than just the web browser - so thanks!)

However,

now it's saying everything is up to date when I have a new file on the editor but not locally.
As a test I also added a new file locally and it still says the diff is nothing.

Installed from the main branch 2 days ago (so up to date and *was* working).

config:
```bash
PLAYCANVAS_API_KEY:<redacted>
PLAYCANVAS_BASE_URL: https://playcanvas.com
PLAYCANVAS_PROJECT_ID: 854449
PLAYCANVAS_BRANCH_ID: a7c38dfb-fdd8-408d-95bf-bf486b3fea2b
PLAYCANVAS_TARGET_DIR: /Users/tobowers/code/play-glad
PLAYCANVAS_BAD_FILE_REG: /^\.|~$/
PLAYCANVAS_BAD_FOLDER_REG: /\./
PLAYCANVAS_USE_CWD_AS_TARGET: undefined
PLAYCANVAS_INCLUDE_REG: undefined
PLAYCANVAS_FORCE_REG: undefined
PLAYCANVAS_DRY_RUN: undefined
PLAYCANVAS_VERBOSE: 1
```

Not sure if this is related or not but I created a checkpoint on the editor before it stopped working.

**Comment by yaustar** [comment] 2021-12-08 13:09
Just want to do some basic troubleshooting:

- Have you created any branches in the project? If so, is it the same branch id as in the config you've displayed above?
- Have you tried a clean folder for the project on your PC

**Comment by tobowers** [comment] 2021-12-09 10:34
> 

I have not created any branches and all the numbers line up. I tried deleting all the files locally and diffAll still returns nothing.

However... a new blank directory *does* return the diff.

**Comment by tobowers** [comment] 2021-12-09 11:03
> 

But editing locally now shows no diff and yet the file is *empty* in the editor.

**Comment by yaustar** [comment] 2021-12-09 11:04
Ok, will have to pull in the developer @zachpeterpaul to take a look

**Comment by yaustar** [comment] 2021-12-10 17:32
We think this may have been caused by a bug in a deployment that caused this issue: https://forum.playcanvas.com/t/solved-unauthorized-when-trying-to-edit-my-own-files/23288

This is fixed now, can you retry please?

**Closed** 2022-03-01 00:40 UTC
Labels: bug
