### ISSUE TITLE
PCWatch sometimes corrupts files

### ISSUE THREAD

**Issue by yorschor** [playcanvas/playcanvas-sync#11] opened 2020-09-02 13:24 UTC
I had this happen 3 times by now. The PCWatch console shows some kind of "UnhandledPromiseRejectionWarning" or similar. Following saves to the local file will no longer sync. In the online editor the file is no longer able to open and must be deleted and then created again copy pasting the old code in there.

**Comment by zachpeterpaul** [comment] 2020-09-02 17:55
Please double-check that the capitalization in your sync config file is correct/matches your file system. Also pcsync uses third party modules to listen to low level os events, and those modules may have limitations for certain os’s. In the worst case you may have to settle for a modified/simplified workflow.

**Comment by willeastcott** [comment] 2020-09-02 18:55
Are there specific steps that can reproduce this issue? That would definitely help isolate what's going on.

**Comment by yorschor** [comment] 2020-09-03 07:16
Unfortunately I don´t now how to reproduce at this time.
I will post the console log here as soon as it happens next time.  
For now I assume that its happening when PCWatch tries to update the file and at the same time something else was going wrong on the server (Always when that was happening one of those "UnhandledPromiseRejection" was present in the console)

**Comment by yorschor** [comment] 2020-10-12 15:13
Got it.  
```
(node:15052) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - "{\"error\":\"Internal server error\"}"
    at new StatusCodeError (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request-promise-core\lib\plumbing.js:46:31)    
    at Request.self.callback (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
```

Thats the error that corrupts the file. 

Following that the file seems to no longer exist on the server. 

```
(node:15052) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - "{\"error\":\"Can't upload a file to an asset without file\"}"
    at new StatusCodeError (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request-promise-core\lib\plumbing.js:46:31)    
    at Request.self.callback (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\myUserFolder\Desktop\playcanvas-sync\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
```

I had the file open in the online editor by accident. There its just says. 'cannot save "filename"'

**Comment by zachpeterpaul** [comment] 2020-10-12 18:05
Thank you for sharing this. Have other issues been occurring lately, that you were having some time ago? We had some server-side issues around that time, which have been resolved now. 
As our readme mentions, editing a file in the online editor while running pcwatch is not supported by design: the invariant is that pcwatch never alters local files to guarantee their integrity, thus it cannot pull any changes being made online. If pcwatch tried to detect changes to remote files between its updates, it would slow it down too much. The error you are seeing happens on the backend because of the conflicting edits.
When using pcwatch, it's better to keep local files in git, view them as the authoritative version of your project, and ensure that the remote versions are always simply exact replicas of what you have locally. 
Also, pcwatch depends on low-level OS-specific code to detect real-time changes to your file system. If it's not working well on your OS, it may be better not to use it, and propagate local changes to PlayCanvas using pcsync push/pushAll.

**Comment by yorschor** [comment] 2020-10-13 08:40
Hi  @zachpeterpaul thanks for the quick answer. 
pcwatch has been behaving really well lately which is why it took me so long to provide the error. 
I only have the online editor open at times for checking if everything is updating properly. (Or when I forget to close it.) I am not making any changes to the online file while pcwatch is running. 

You mentioned low level os events. I noticed that pcwatch doesn't seem to like it when I have to many other processes running. Especially running some kind of installation freaks it out completely. 

_"UnhandledPromiseRejectionWarning: RequestError: Error: form-data: EISDIR: illegal operation on a directory, read"_ still occur rather often but don't break anything. Hitting save again does the job most of the times. 
Beside that pcwatch itself is running smoothly more often than not.  

pcsync Pull is a different topic though not producing the same hierarchy as online most of the time. But that's in another issue ^^ 

The main problem with files getting corrupted is that the files then no longer exist on the server (0 bytes storage occupied). Maybe a "reimport script" option in the editor would solve that problem so the asset id isn't lost due to recreating the file.

**Comment by zachpeterpaul** [comment] 2021-04-06 16:49
All should now work correctly, please try the latest version of playcanvas-sync

**Comment by willeastcott** [comment] 2021-04-07 12:27
Closing since `pcwatch` now works on Windows. Please reopen if you continue to experience problems with this.

**Closed by willeastcott** 2021-04-07 12:27 UTC
Labels: bug
